### ISSUE TITLE
Declare the plugin breaks mkdocs

### ISSUE THREAD

**Issue by conjderumba** [LukeCarrier/mkdocs-drawio-exporter#7]
Hi!

I think the plugin is not working with mkdocs 1.1

If I declare the plugin, "mkdocs serve" don't start, and I get this error:

 File "/Users/jma/.asdf/installs/python/3.7.6/lib/python3.7/site-packages/mkdocsdrawioexporter/__init__.py", line 2, in <module>
    from .plugin import DrawIoExporterPlugin
  File "/Users/jma/.asdf/installs/python/3.7.6/lib/python3.7/site-packages/mkdocsdrawioexporter/plugin.py", line 9, in <module>
    from mkdocs.utils import copy_file, string_types
ImportError: cannot import name 'string_types' from 'mkdocs.utils' (/Users/jma/.asdf/installs/python/3.7.6/lib/python3.7/site-packages/mkdocs/utils/__init__.py)Is this plugin because if I remove it, mkdocs serve starts wihout problem.

Thanks

**Comment by conjderumba** [comment]
File "/Users/jma/.asdf/installs/python/3.7.6/lib/python3.7/site-packages/mkdocsdrawioexporter/__init__.py", line 2, in <module>
    from .plugin import DrawIoExporterPlugin
  File "/Users/jma/.asdf/installs/python/3.7.6/lib/python3.7/site-packages/mkdocsdrawioexporter/plugin.py", line 9, in <module>
    from mkdocs.utils import copy_file, string_types

**Comment by conjderumba** [comment]
I observed that string_types doesn't exists in mkdocs.utils...

**Comment by LukeCarrier** [comment]
@conjderumba I'm fairly sure this is related to #6. If you want to provide a PR that adds a warning to `README.md` I'll accept it. We'll be upgrading soon and I'll circle back to this then.
